spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: konche
        url: jdbc:mysql://localhost:3306/stotifyplaylistapp?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        # Choose either MySQL 8 or MySQL 5 below
        # For MySQL 8:
        #database-platform: org.hibernate.dialect.MySQL8Dialect
        # For MySQL 5:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update

#  sql:
#    init:
#      mode: always
